//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibraryApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ADMIN HELP
        ///
        ///You are in the home library application.
        ///
        ///To automatically fill the library with test data, click the &quot;Library Autocomplete&quot; button.
        ///
        ///To view sections of the library, click the &quot;Sections&quot; button and select the needed genre from the drop-down list. For this genre, a list of books that you can see will appear below.
        ///
        ///If you choose a book, a form with the characteristics of the selected book will be displayed.
        ///
        ///The user can take a book to read by checking the &quot;Read now&quot; or like it by chec [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string AdminHelp {
            get {
                return ResourceManager.GetString("AdminHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] bookTest {
            get {
                object obj = ResourceManager.GetObject("bookTest", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GUEST HELP
        ///
        ///You are in the home library application.
        ///
        ///To automatically fill the library with test data, click the &quot;Library Autocomplete&quot; button.
        ///
        ///To view sections of the library, click the &quot;Sections&quot; button and select the needed genre from the drop-down list. For this genre, a list of books that you can see will appear below.
        ///
        ///If you choose a book, a form with the characteristics of the selected book will be displayed.
        ///
        ///The user can take a book to read by checking the &quot;Read now&quot; or like it by chec [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string GuestHelp {
            get {
                return ResourceManager.GetString("GuestHelp", resourceCulture);
            }
        }
    }
}
